async functions, python sdk
FRINXio/fm-base-workers pull request #37
Opened 2022-12-20 12:52 UTC by Maros-Soltys

2023-01-09 10:56 UTC, Jozefiel requested changes

2023-01-10 14:53 UTC, davidbelusky commented on frinx_python_sdk/src/frinx/workers/uniconfig/cli_worker_test.py
> +import json
I think it would be good to create separate folder for tests like we have in other projects
for ex. 

/frinx_python_sdk/test/workers/uniconfig/cli_worker_test.py

2023-01-13 10:36 UTC, Jozefiel approved these changes

2023-01-13 11:00 UTC, Jozefiel approved these changes

2023-01-13 11:00 UTC, merged