Refactor of RM worker and add features to improve RM
FRINXio/fm-base-workers pull request #39
Opened 2023-02-02 14:29 UTC by Branislav-Karkus

Refactor of resource-manager-worker, add features to util.py so there will be completed and failed response with logs, add logging handler because its one of the dependencies for new RM worker and changed version in setup.py to 1.1.2

2023-02-03 10:38 UTC, Vasyl-9 requested changes

2023-02-03 10:38 UTC, Vasyl-9 commented on frinx_conductor_workers/frinx_conductor_workers/resource_manager_worker.py
>      """
add AlternativeId to response_body in docs

2023-02-03 10:38 UTC, Vasyl-9 commented on frinx_conductor_workers/frinx_conductor_workers/resource_manager_worker.py
>      if alternative_id is not None:
if alternative_id is not None and len(alternative_id) > 0:

2023-02-03 10:38 UTC, Vasyl-9 commented on frinx_conductor_workers/frinx_conductor_workers/uniconfig_worker.py
> -
Why did you change this file?

2023-02-03 10:38 UTC, Vasyl-9 commented on frinx_python_sdk/src/frinx/workers/uniconfig/uniconfig_worker.py
> -
Why did you change this file?

2023-02-03 10:40 UTC, Branislav-Karkus commented on frinx_conductor_workers/frinx_conductor_workers/uniconfig_worker.py
> -
new version of black, which formatted even this file

2023-02-03 10:40 UTC, Branislav-Karkus commented on frinx_python_sdk/src/frinx/workers/uniconfig/uniconfig_worker.py
> -
new version of black, which formatted even this file

2023-02-03 10:43 UTC, Vasyl-9 commented on frinx_conductor_workers/frinx_conductor_workers/uniconfig_worker.py
> -
ok

2023-02-03 10:43 UTC, Vasyl-9 commented on frinx_python_sdk/src/frinx/workers/uniconfig/uniconfig_worker.py
> -
ok

2023-02-03 11:38 UTC, Branislav-Karkus commented on frinx_conductor_workers/frinx_conductor_workers/resource_manager_worker.py
>      """
done

2023-02-03 11:38 UTC, Branislav-Karkus commented on frinx_conductor_workers/frinx_conductor_workers/resource_manager_worker.py
>      if alternative_id is not None:
done

2023-02-08 11:15 UTC, Vasyl-9 approved these changes

2023-02-08 11:16 UTC, Vasyl-9 approved these changes

2023-02-08 11:19 UTC, Jozefiel approved these changes

2023-02-08 11:20 UTC, merged