Fix for RM worker and update 2 allocate wfs
FRINXio/fm-base-workers pull request #49
Opened 2023-03-21 17:43 UTC by Branislav-Karkus

- Change version to 1.1.5
- Fix for update_alt_id task in resource manager worker
- Change input params value in 2 allocate WFs

2023-03-21 21:44 UTC, Vasyl-9 requested changes

2023-03-21 21:44 UTC, Vasyl-9 commented on frinx_conductor_workers/frinx_conductor_workflows/resource_manager_workflows/Allocate_IPv6_Prefix_Resource.json
> -    "{\"pool_name\":{\"value\":\"\",\"description\":\"Pool name\",\"type\":\"string\"}, \"description\":{\"value\":\"\",\"description\":\"[OPTIONAL] Description for resource\",\"type\":\"string\"}, \
Why you delete this example value?

2023-03-21 21:44 UTC, Vasyl-9 commented on frinx_conductor_workers/frinx_conductor_workflows/resource_manager_workflows/Allocate_IPv4_Prefix_Resource.json
> +        "{\"pool_name\":{\"value\":\"\",\"description\":\"Pool name\",\"type\":\"string\"}, \"description\":{\"value\":\"\",\"description\":\"[OPTIONAL] Description for resource\",\"type\":\"string\"
Why you delete this example value?

2023-03-22 09:13 UTC, Branislav-Karkus commented on frinx_conductor_workers/frinx_conductor_workflows/resource_manager_workflows/Allocate_IPv6_Prefix_Resource.json
> -    "{\"pool_name\":{\"value\":\"\",\"description\":\"Pool name\",\"type\":\"string\"}, \"description\":{\"value\":\"\",\"description\":\"[OPTIONAL] Description for resource\",\"type\":\"string\"}, \
In new commit is this change reverted

2023-03-22 09:13 UTC, Branislav-Karkus commented on frinx_conductor_workers/frinx_conductor_workflows/resource_manager_workflows/Allocate_IPv4_Prefix_Resource.json
> +        "{\"pool_name\":{\"value\":\"\",\"description\":\"Pool name\",\"type\":\"string\"}, \"description\":{\"value\":\"\",\"description\":\"[OPTIONAL] Description for resource\",\"type\":\"string\"
In new commit is this change reverted

2023-03-22 09:14 UTC, Vasyl-9 requested changes

2023-03-22 09:25 UTC, Branislav-Karkus commented on frinx_conductor_workers/frinx_conductor_workers/resource_manager_worker.py
>      body = query_recently_active_resources_template.render()
Done

2023-03-22 09:29 UTC, Vasyl-9 approved these changes

2023-03-22 09:29 UTC, merged