Performance / system tests
FRINXio/fm-base-workers pull request #54
Opened 2023-04-03 13:28 UTC by marosmars

#### Checklist
- [ ] Add description to the PR
- [ ] Bump version in setup.py for dedicated python package

2023-04-04 12:29 UTC, Jozefiel approved these changes

2023-04-04 16:19 UTC, stanislav-chlebec requested changes
Very nice.
I learnt a lot from it.
Thanks.

2023-04-05 06:29 UTC, marosmars commented on system_tests/tests/frinx/test_performance.py
> +        stats = await collect_stats(session, executed_ids[0::SAMPLING_RATE])
yes, so that we don't query every single workflow out of e.g. 10k from the long running test.

2023-04-05 06:31 UTC, marosmars commented on system_tests/tests/frinx/test_performance.py
> +        assert stats["failed_workflows"] == 0
yeah, the aim is to collect stats. But failed workflows would indicate an error somewhere which would pollute the stats and make them unusable.

We should develop a different set of regression tests that would assert the standard behavior, outside of this file

So I would keep that single assert to make sure to fail fast in case of any failures

2023-04-05 06:32 UTC, marosmars commented on system_tests/tests/frinx/test_performance.py
> +CONDUCTOR_URL = "http://localhost:8080/api/"
will change

2023-04-05 06:33 UTC, marosmars commented on system_tests/tests/frinx/test_performance.py
> +async def test_performance_simple_wf():
It is both a test and a function. Maybe having it as a test is redundant ... maybe we can mark the 2 tests with different marks : QUICK / LONG so that we can run a shorter version of these tests on merge in the future ...

I will keep it as is for now

2023-04-05 06:36 UTC, marosmars commented on system_tests/tests/frinx/test_performance.py
> +
It is on line 210. 

`        LOGGER.info("Execution stats: %s", stats)`

all_stats is present only in the "long" test case

2023-04-05 06:38 UTC, marosmars commented
@stanislav-chlebec thx for review. I have fixed the missing env var. Other comments have I have responded to.

2023-04-05 07:16 UTC, stanislav-chlebec approved these changes

2023-04-05 08:03 UTC, merged