Changes due to changes in RM2.0.0
FRINXio/fm-base-workers pull request #78
Opened 2023-07-21 08:09 UTC by Branislav-Karkus

Version change from 1.1.12 to 1.1.13

2023-07-27 11:31 UTC, Vasyl-9 requested changes

2023-07-27 11:31 UTC, Vasyl-9 commented on frinx_conductor_workers/frinx_conductor_workers/resource_manager_worker.py
> +            nodes{
Shouldn't it just be node instead of nodes here?
And please add 1 empty space between word and {

2023-07-27 11:35 UTC, Branislav-Karkus commented on frinx_conductor_workers/frinx_conductor_workers/resource_manager_worker.py
> +            nodes{
Done.

2023-07-27 11:37 UTC, Vasyl-9 requested changes

2023-07-27 11:37 UTC, Vasyl-9 commented on frinx_conductor_workers/frinx_conductor_workers/resource_manager_worker.py
> +                    "edges": [
Should it be "edges": [ { "node" } ] or just "edges": { "node" }. Please investigate it and unify it.

2023-08-01 09:45 UTC, Branislav-Karkus commented on frinx_conductor_workers/frinx_conductor_workers/resource_manager_worker.py
> +                    "edges": [
no, the only wrong thing on this output was "QueryResourcePools": [{"edges}], it should be "QueryResourcePools": {"edges"} so i already fixed it.
correct output is:
{
  "result": {
    "data": {
      "QueryResourcePools": {
        "edges": [
          {
            "node": {
              "id": "21474837189"
            }
          }
        ]
      }
    }
  }
}

2023-08-01 09:59 UTC, Vasyl-9 approved these changes

2023-08-01 09:59 UTC, merged